Random change
MohistMC/Mohist pull request #1737
Opened 2021-09-16 09:15 UTC by 1798643961

Move some code for better handle
Handle worldevent
fix cast error

2021-09-16 13:24 UTC, 1798643961 commented
![image](https://user-images.githubusercontent.com/40519136/133620155-aed5200c-e05c-4b3c-8986-82df2b03e290.png)

2021-09-16 16:01 UTC, Romaindu35 commented
I have run again the workflows, I think that forge maven repository was down when latest workflows was execute !

2021-09-16 16:07 UTC, Romaindu35 requested changes

2021-09-16 16:07 UTC, Romaindu35 commented on patches/minecraft/net/minecraft/entity/Entity.java.patch
> -+   public void setBukkitEntity(CraftEntity bukkitEntity) {
This function is always delete 🙃

2021-09-17 00:22 UTC, 1798643961 commented on patches/minecraft/net/minecraft/entity/Entity.java.patch
> -+   public void setBukkitEntity(CraftEntity bukkitEntity) {
。。。。。。
I moved the code in Entity.class
Don't worry

2021-09-17 05:10 UTC, Romaindu35 approved these changes

2021-09-17 05:10 UTC, Romaindu35 commented on patches/minecraft/net/minecraft/entity/Entity.java.patch
> -+   public void setBukkitEntity(CraftEntity bukkitEntity) {
Ok

2021-09-18 10:32 UTC, merged