Fixed an issue where the CraftChunkSnapshot chunk snapshot was not getting the correct mod block id
MohistMC/Mohist pull request #2106
Opened 2022-03-08 11:59 UTC by mirroI

When calling the chunk.getHighestBlockYAt(x, z) method from the bukkit, blocks from the mod were ignored.

2022-03-08 20:27 UTC, Romaindu35 requested changes
Please don't add tags for author. There are github history for this.

2022-03-08 20:27 UTC, Romaindu35 commented on src/main/java/org/bukkit/craftbukkit/v1_12_R1/CraftChunk.java
> +                    // mirrol start
Please use ```// Mohist start```

2022-03-08 20:27 UTC, Romaindu35 commented on src/main/java/org/bukkit/craftbukkit/v1_12_R1/CraftChunk.java
> +                    // mirrol end
Please use ```// Mohist end```

2022-03-08 20:27 UTC, Romaindu35 commented on src/main/java/org/bukkit/craftbukkit/v1_12_R1/CraftChunk.java
> +                NibbleArray blockIdExtensionData = cs[i].getData().getDataForNBT(rawIds, data); // mirrol
Please use ``` // Mohist ```

2022-03-09 16:41 UTC, Romaindu35 approved these changes
It is good (for the typo only, I don't test the code)

2022-03-09 17:01 UTC, Serega007RU commented
This PR does not fix chunk.getHighestBlockYAt unfortunately but fixes getting block id from CraftChunkSnapshot

2022-03-15 09:37 UTC, merged